name: Source Code Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Whitespace Errors Check
      run: git diff-index --check --cached 4b825dc642cb6eb9a060e54bf8d69288fbee4904
